name: Test, Build and Deploy

on: push

jobs:
  build-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    env:
      API_ORIGIN: ${{ vars.API_ORIGIN }}
      API_PATH: /api/v1/trpc
      CLIENT_IMAGE_TAG: client-${{ github.sha }}
      SERVER_IMAGE_TAG: server-${{ github.sha }}
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      - name: 'Build and push client container'
        run: |-
          docker build -t "${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/app/${{ env.APP }}:$CLIENT_IMAGE_TAG" ./app/client
          docker push "${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/app/$CLIENT_IMAGE_TAG"

      - name: 'Build and push server container'
        run: |-
          docker build -t "${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/app/$SERVER_IMAGE_TAG" ./app/server
          docker push "${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/app/$SERVER_IMAGE_TAG"

      - name: Deploy client to Cloud Run
        run: |
          gcloud run deploy client-service \
            --image gcr.io/${{ secrets.PROJECT_ID }}/client \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --allow-unauthenticated

      - name: Deploy server to Cloud Run
        run: |
          gcloud run deploy server-service \
            --image gcr.io/${{ secrets.PROJECT_ID }}/server \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --allow-unauthenticated
